version: "3"

services:
  tooljet:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-ce:${SOFTWARE_VERSION_TAG}
    restart: always
    env_file: .env
    ports:
      - 172.17.0.1:5179:80
    depends_on:
      - postgres
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
    command: npm run start:prod

  postgres:
    image: elestio/postgres:15
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - 172.17.0.1:39393:5432

  postgrest:
    image: postgrest/postgrest:v10.1.1.20221215
    restart: always
    depends_on:
      - postgres
    env_file: .env
    environment:
      - PGRST_SERVER_PORT=80

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:2019:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
